### ISSUE TITLE
Unable to compile the Project

### ISSUE THREAD

**Issue by MohamedHz** [samn/riemann-syntax-check#4]
Hi,

Unable to compile the project and we are facing an error with java exceptions. The logs are below:

Compiling riemann-syntax-check
java.lang.NoClassDefFoundError: clojure/lang/Tuple, compiling:(riemann_syntax_check.clj:1:1)
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/lang/Tuple, compiling:(riemann_syntax_check.clj:1:1)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3558)
        at clojure.lang.Compiler.compile1(Compiler.java:7226)
        at clojure.lang.Compiler.compile1(Compiler.java:7216)
        at clojure.lang.Compiler.compile(Compiler.java:7292)
        at clojure.lang.RT.compile(RT.java:398)
        at clojure.lang.RT.load(RT.java:438)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$compile$fn__5071.invoke(core.clj:5652)
        at clojure.core$compile.invoke(core.clj:5651)
        at user$eval20$fn__29.invoke(form-init5589614143195693041.clj:1)
        at user$eval20.invoke(form-init5589614143195693041.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)

**Comment by samn** [comment]
Sorry about that @MohamedHz! I just pushed a fix for this. Can you pull master and try again?

**Comment by MohamedHz** [comment]
Thankk you @samn the project was compiled successfully.
